################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_burtc.c \
/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_cmu.c \
/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_core.c \
/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_emu.c \
/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_eusart.c \
/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_gpio.c \
/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_ldma.c \
/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_msc.c \
/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_rtcc.c \
/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_system.c \
/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_timer.c \
/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_usart.c 

OBJS += \
./gecko_sdk_4.4.4/platform/emlib/src/em_burtc.o \
./gecko_sdk_4.4.4/platform/emlib/src/em_cmu.o \
./gecko_sdk_4.4.4/platform/emlib/src/em_core.o \
./gecko_sdk_4.4.4/platform/emlib/src/em_emu.o \
./gecko_sdk_4.4.4/platform/emlib/src/em_eusart.o \
./gecko_sdk_4.4.4/platform/emlib/src/em_gpio.o \
./gecko_sdk_4.4.4/platform/emlib/src/em_ldma.o \
./gecko_sdk_4.4.4/platform/emlib/src/em_msc.o \
./gecko_sdk_4.4.4/platform/emlib/src/em_rtcc.o \
./gecko_sdk_4.4.4/platform/emlib/src/em_system.o \
./gecko_sdk_4.4.4/platform/emlib/src/em_timer.o \
./gecko_sdk_4.4.4/platform/emlib/src/em_usart.o 

C_DEPS += \
./gecko_sdk_4.4.4/platform/emlib/src/em_burtc.d \
./gecko_sdk_4.4.4/platform/emlib/src/em_cmu.d \
./gecko_sdk_4.4.4/platform/emlib/src/em_core.d \
./gecko_sdk_4.4.4/platform/emlib/src/em_emu.d \
./gecko_sdk_4.4.4/platform/emlib/src/em_eusart.d \
./gecko_sdk_4.4.4/platform/emlib/src/em_gpio.d \
./gecko_sdk_4.4.4/platform/emlib/src/em_ldma.d \
./gecko_sdk_4.4.4/platform/emlib/src/em_msc.d \
./gecko_sdk_4.4.4/platform/emlib/src/em_rtcc.d \
./gecko_sdk_4.4.4/platform/emlib/src/em_system.d \
./gecko_sdk_4.4.4/platform/emlib/src/em_timer.d \
./gecko_sdk_4.4.4/platform/emlib/src/em_usart.d 


# Each subdirectory must supply rules for building sources it contributes
gecko_sdk_4.4.4/platform/emlib/src/em_burtc.o: /Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_burtc.c gecko_sdk_4.4.4/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220SC12WGA=1' '-DSL_BOARD_NAME="BRD4310A"' '-DSL_BOARD_REV="A05"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCHIPSEL_594X=1' '-DADI_DEBUG=1' -I"/Users/xinye/SimplicityStudio/v5_workspace/test/config" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/autogen" -I"/Users/xinye/SimplicityStudio/v5_workspace/test" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/Device/SiliconLabs/BGM22/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//app/common/util/app_assert" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/board/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/CMSIS/Core/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/configuration_over_swo/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/driver/debug/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/device_init/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/dmadrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/init/gpio_simple" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/gpiointerrupt/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/iostream/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/toolchain/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/system/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/sleeptimer/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/spidrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/udelay/inc" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/ad5940lib" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.4/platform/emlib/src/em_burtc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.4/platform/emlib/src/em_cmu.o: /Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_cmu.c gecko_sdk_4.4.4/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220SC12WGA=1' '-DSL_BOARD_NAME="BRD4310A"' '-DSL_BOARD_REV="A05"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCHIPSEL_594X=1' '-DADI_DEBUG=1' -I"/Users/xinye/SimplicityStudio/v5_workspace/test/config" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/autogen" -I"/Users/xinye/SimplicityStudio/v5_workspace/test" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/Device/SiliconLabs/BGM22/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//app/common/util/app_assert" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/board/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/CMSIS/Core/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/configuration_over_swo/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/driver/debug/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/device_init/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/dmadrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/init/gpio_simple" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/gpiointerrupt/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/iostream/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/toolchain/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/system/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/sleeptimer/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/spidrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/udelay/inc" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/ad5940lib" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.4/platform/emlib/src/em_cmu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.4/platform/emlib/src/em_core.o: /Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_core.c gecko_sdk_4.4.4/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220SC12WGA=1' '-DSL_BOARD_NAME="BRD4310A"' '-DSL_BOARD_REV="A05"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCHIPSEL_594X=1' '-DADI_DEBUG=1' -I"/Users/xinye/SimplicityStudio/v5_workspace/test/config" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/autogen" -I"/Users/xinye/SimplicityStudio/v5_workspace/test" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/Device/SiliconLabs/BGM22/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//app/common/util/app_assert" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/board/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/CMSIS/Core/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/configuration_over_swo/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/driver/debug/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/device_init/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/dmadrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/init/gpio_simple" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/gpiointerrupt/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/iostream/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/toolchain/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/system/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/sleeptimer/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/spidrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/udelay/inc" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/ad5940lib" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.4/platform/emlib/src/em_core.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.4/platform/emlib/src/em_emu.o: /Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_emu.c gecko_sdk_4.4.4/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220SC12WGA=1' '-DSL_BOARD_NAME="BRD4310A"' '-DSL_BOARD_REV="A05"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCHIPSEL_594X=1' '-DADI_DEBUG=1' -I"/Users/xinye/SimplicityStudio/v5_workspace/test/config" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/autogen" -I"/Users/xinye/SimplicityStudio/v5_workspace/test" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/Device/SiliconLabs/BGM22/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//app/common/util/app_assert" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/board/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/CMSIS/Core/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/configuration_over_swo/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/driver/debug/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/device_init/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/dmadrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/init/gpio_simple" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/gpiointerrupt/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/iostream/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/toolchain/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/system/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/sleeptimer/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/spidrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/udelay/inc" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/ad5940lib" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.4/platform/emlib/src/em_emu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.4/platform/emlib/src/em_eusart.o: /Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_eusart.c gecko_sdk_4.4.4/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220SC12WGA=1' '-DSL_BOARD_NAME="BRD4310A"' '-DSL_BOARD_REV="A05"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCHIPSEL_594X=1' '-DADI_DEBUG=1' -I"/Users/xinye/SimplicityStudio/v5_workspace/test/config" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/autogen" -I"/Users/xinye/SimplicityStudio/v5_workspace/test" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/Device/SiliconLabs/BGM22/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//app/common/util/app_assert" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/board/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/CMSIS/Core/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/configuration_over_swo/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/driver/debug/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/device_init/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/dmadrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/init/gpio_simple" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/gpiointerrupt/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/iostream/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/toolchain/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/system/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/sleeptimer/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/spidrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/udelay/inc" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/ad5940lib" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.4/platform/emlib/src/em_eusart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.4/platform/emlib/src/em_gpio.o: /Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_gpio.c gecko_sdk_4.4.4/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220SC12WGA=1' '-DSL_BOARD_NAME="BRD4310A"' '-DSL_BOARD_REV="A05"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCHIPSEL_594X=1' '-DADI_DEBUG=1' -I"/Users/xinye/SimplicityStudio/v5_workspace/test/config" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/autogen" -I"/Users/xinye/SimplicityStudio/v5_workspace/test" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/Device/SiliconLabs/BGM22/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//app/common/util/app_assert" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/board/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/CMSIS/Core/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/configuration_over_swo/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/driver/debug/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/device_init/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/dmadrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/init/gpio_simple" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/gpiointerrupt/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/iostream/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/toolchain/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/system/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/sleeptimer/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/spidrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/udelay/inc" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/ad5940lib" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.4/platform/emlib/src/em_gpio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.4/platform/emlib/src/em_ldma.o: /Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_ldma.c gecko_sdk_4.4.4/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220SC12WGA=1' '-DSL_BOARD_NAME="BRD4310A"' '-DSL_BOARD_REV="A05"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCHIPSEL_594X=1' '-DADI_DEBUG=1' -I"/Users/xinye/SimplicityStudio/v5_workspace/test/config" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/autogen" -I"/Users/xinye/SimplicityStudio/v5_workspace/test" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/Device/SiliconLabs/BGM22/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//app/common/util/app_assert" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/board/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/CMSIS/Core/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/configuration_over_swo/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/driver/debug/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/device_init/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/dmadrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/init/gpio_simple" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/gpiointerrupt/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/iostream/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/toolchain/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/system/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/sleeptimer/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/spidrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/udelay/inc" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/ad5940lib" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.4/platform/emlib/src/em_ldma.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.4/platform/emlib/src/em_msc.o: /Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_msc.c gecko_sdk_4.4.4/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220SC12WGA=1' '-DSL_BOARD_NAME="BRD4310A"' '-DSL_BOARD_REV="A05"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCHIPSEL_594X=1' '-DADI_DEBUG=1' -I"/Users/xinye/SimplicityStudio/v5_workspace/test/config" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/autogen" -I"/Users/xinye/SimplicityStudio/v5_workspace/test" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/Device/SiliconLabs/BGM22/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//app/common/util/app_assert" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/board/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/CMSIS/Core/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/configuration_over_swo/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/driver/debug/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/device_init/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/dmadrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/init/gpio_simple" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/gpiointerrupt/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/iostream/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/toolchain/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/system/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/sleeptimer/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/spidrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/udelay/inc" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/ad5940lib" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.4/platform/emlib/src/em_msc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.4/platform/emlib/src/em_rtcc.o: /Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_rtcc.c gecko_sdk_4.4.4/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220SC12WGA=1' '-DSL_BOARD_NAME="BRD4310A"' '-DSL_BOARD_REV="A05"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCHIPSEL_594X=1' '-DADI_DEBUG=1' -I"/Users/xinye/SimplicityStudio/v5_workspace/test/config" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/autogen" -I"/Users/xinye/SimplicityStudio/v5_workspace/test" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/Device/SiliconLabs/BGM22/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//app/common/util/app_assert" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/board/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/CMSIS/Core/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/configuration_over_swo/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/driver/debug/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/device_init/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/dmadrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/init/gpio_simple" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/gpiointerrupt/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/iostream/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/toolchain/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/system/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/sleeptimer/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/spidrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/udelay/inc" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/ad5940lib" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.4/platform/emlib/src/em_rtcc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.4/platform/emlib/src/em_system.o: /Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_system.c gecko_sdk_4.4.4/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220SC12WGA=1' '-DSL_BOARD_NAME="BRD4310A"' '-DSL_BOARD_REV="A05"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCHIPSEL_594X=1' '-DADI_DEBUG=1' -I"/Users/xinye/SimplicityStudio/v5_workspace/test/config" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/autogen" -I"/Users/xinye/SimplicityStudio/v5_workspace/test" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/Device/SiliconLabs/BGM22/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//app/common/util/app_assert" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/board/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/CMSIS/Core/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/configuration_over_swo/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/driver/debug/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/device_init/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/dmadrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/init/gpio_simple" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/gpiointerrupt/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/iostream/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/toolchain/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/system/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/sleeptimer/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/spidrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/udelay/inc" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/ad5940lib" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.4/platform/emlib/src/em_system.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.4/platform/emlib/src/em_timer.o: /Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_timer.c gecko_sdk_4.4.4/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220SC12WGA=1' '-DSL_BOARD_NAME="BRD4310A"' '-DSL_BOARD_REV="A05"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCHIPSEL_594X=1' '-DADI_DEBUG=1' -I"/Users/xinye/SimplicityStudio/v5_workspace/test/config" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/autogen" -I"/Users/xinye/SimplicityStudio/v5_workspace/test" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/Device/SiliconLabs/BGM22/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//app/common/util/app_assert" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/board/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/CMSIS/Core/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/configuration_over_swo/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/driver/debug/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/device_init/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/dmadrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/init/gpio_simple" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/gpiointerrupt/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/iostream/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/toolchain/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/system/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/sleeptimer/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/spidrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/udelay/inc" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/ad5940lib" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.4/platform/emlib/src/em_timer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.4.4/platform/emlib/src/em_usart.o: /Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2/platform/emlib/src/em_usart.c gecko_sdk_4.4.4/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DBGM220SC12WGA=1' '-DSL_BOARD_NAME="BRD4310A"' '-DSL_BOARD_REV="A05"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCHIPSEL_594X=1' '-DADI_DEBUG=1' -I"/Users/xinye/SimplicityStudio/v5_workspace/test/config" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/autogen" -I"/Users/xinye/SimplicityStudio/v5_workspace/test" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/Device/SiliconLabs/BGM22/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//app/common/util/app_assert" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/board/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/CMSIS/Core/Include" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/configuration_over_swo/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/driver/debug/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/device_init/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/dmadrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/common/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emlib/init/gpio_simple" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/gpiointerrupt/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/iostream/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/common/toolchain/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/system/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/sleeptimer/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/emdrv/spidrv/inc" -I"/Users/xinye/SimplicityStudio/SDKs/gecko_sdk_2//platform/service/udelay/inc" -I"/Users/xinye/SimplicityStudio/v5_workspace/test/ad5940lib" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.4.4/platform/emlib/src/em_usart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


